package conflicts

var ERR_CUSTOMER_EMAIL_ALREADY_EXISTS = ErrorConflicts{
	MessageId: "ERR_CUSTOMER_EMAIL_ALREADY_EXISTS",
	Message:   "ERR_CUSTOMER_EMAIL_ALREADY_EXISTS",
}

var ERR_CUSTOMER_IDENTIFICATION_ALREADY_EXISTS = ErrorConflicts{
	MessageId: "ERR_CUSTOMER_IDENTIFICATION_ALREADY_EXISTS",
	Message:   "ERR_CUSTOMER_IDENTIFICATION_ALREADY_EXISTS",
}

var ERR_CUSTOMER_PHONE_ALREADY_EXISTS = ErrorConflicts{
	MessageId: "ERR_CUSTOMER_PHONE_ALREADY_EXISTS",
	Message:   "ERR_CUSTOMER_PHONE_ALREADY_EXISTS",
}

var ERR_CUSTOMER_EMAIL_NOT_FOUND = ErrorConflicts{
	MessageId: "ERR_CUSTOMER_EMAIL_NOT_FOUND",
	Message:   "ERR_CUSTOMER_EMAIL_NOT_FOUND",
}

var ERR_CUSTOMER_NOT_FOUND = ErrorConflicts{
	MessageId: "ERR_CUSTOMER_NOT_FOUND",
	Message:   "ERR_CUSTOMER_NOT_FOUND",
}
