nombre: Ir

en: [push]

trabajos:
  construir:

    se ejecuta en: ubuntu-latest
    estrategia:
      matriz:
        versión go: [ '1.19', '1.20', '1.21.x' ]

    pasos:
      - usos: acciones/checkout@v4
      - nombre: Configurar Go ${{ matrix.go-version }}
        usos: acciones/setup-go@v5
        con:
          go-version: ${{ matrix.go-version }}
      # Puede probar su matriz imprimiendo la versión actual de Go
      - nombre: Mostrar la versión de Go
        ejecutar: ir versión
