name: Deploy to AKS

run-name: ${{ github.actor }}
on: 
  push:
    branches: [ main-gh-actions ]
jobs:
  prepare_env:
    runs-on: [ ubuntu-latest ]
    steps:
      - name: Clone project
        uses: actions/checkout@v4
