name: learn-github-actions
run-name: ${{ github.actor }} is learning GitHub Actions
on: [ push ]
jobs:
  check-bats-version:
    runs-on: [self-hosted]
    steps:
      - run: echo "Estoy en $(pwd)"
      - run: ls -la
      - run: chmod 111 ./test.sh
      - run: ls -la
      - run: ./test.sh
