name: Deploy to AKS
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on: [ push ]
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
        - name: Clonar el repositorio
          uses: actions/checkout@v3
