name: learn-github-actions-2
run-name: ${{ github.actor }} is learning GitHub Actions

on:
  push: 
    branches: 
      - 'feature'

jobs:
  hello_world_job:
    # runs-on: [self-hosted]
    runs-on: [ubuntu-lasted]
    name: A job to say hello
    steps:
      - name: Hello world action step
        id: hello
        uses: ./.github/actions/hello-world-docker-action
        with:
          who-to-greet: 'Mona the Octocat2'
      # Use the output from the `hello` step
      - name: Get the output time
        run: echo "The time was ${{ steps.hello.outputs.time }}"
